name: "ha-mcp-server"
version: "0.1.3"
slug: "ha_mcp_server"
description: "Model Context Protocol (MCP) server for Home Assistant."
url: "https://github.com/kaichiachen/ha-mcp-server"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  ha_url: "http://supervisor/core"
  ha_token: ""
schema:
  ha_url: str
  ha_token: str
ports:
  8000/tcp: 8000
image: "ghcr.io/kaichiachen/ha-mcp-server"
